### ISSUE TITLE
Bug: Latest HA Core update 2024.5.0 breaks notification entities.

### ISSUE THREAD

**Issue by hacshacdgacs** [hass-agent/HASS.Agent-Integration#2] opened 2024-05-01 21:04 UTC
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
The latest HA Core update (2024.5.0) stops hass.agent from creating any notify entities. 

**To Reproduce**
1. Update HA Core to 2024.5.0
2. When the server restarts it won't have any hass.agent notification entities.

**Expected behavior**
That the notify entities are created like normal.

**Misc info (please complete the following information):**
![image](https://github.com/hass-agent/HASS.Agent/assets/85550264/6464e32d-2eda-49ca-9dfb-e7790c12bdf0)
 - Windows' UI language: English
 - HASS.Agent version: 2.0.1 and 2.1.0 Beta

**Comment by amadeo-alex** [comment] 2024-05-11 20:24
Aaand moved to the proper repository :D

**Comment by Mabaelst1964** [comment] 2024-05-13 09:53
I have tried everything on this site!! But nothing works for me at all. What am I doing wrong?

**Comment by amadeo-alex** [comment] 2024-05-13 09:56
You'll need to provide us with more information because without it it's guessing what might be wrong - what exactly is not working, has it been working before, what you've tried, are there any Home Assistant errors in the log?

**Comment by Mabaelst1964** [comment] 2024-05-13 10:19
I installed the HASS.agent2 in HA and also in Windows. I restarted HA. All connections are OK but I still don't see 'notify_entity and no media player entity. I'm fairly new here!

**Comment by Mabaelst1964** [comment] 2024-05-13 10:21
<img width="458" alt="image" src="https://github.com/hass-agent/HASS.Agent-Integration/assets/57778382/5fe8963e-23a6-46d4-866e-d200dc5862bd">

**Comment by Mabaelst1964** [comment] 2024-05-13 10:22
And as far as I can see as a newbie, there are no mentions of HASS.agent in the logs

**Comment by amadeo-alex** [comment] 2024-05-13 10:45
Can we move this conversation to discord please? - https://discord.gg/ed4B4cdG - as I'm not sure that your issue is related to this one I don't want to spam all the participants of this thread

**Comment by entirelynutz** [comment] 2024-05-18 02:45
@amadeo-alex I'm a little confused. I deleted all my computers and removed the legacy HASS.Agent from my Home Assistant. I then installed your forked version under HACS custom repository. Unfortunately I don't see the agent anywhere nor do I see my computers showing up. Do I need to reinstall the original HASS.Agent, edit the files as you posted earlier then install your forked version?

I guess what I am asking is what are the required steps to go from the broken original HASS.Agent to you corrected/working version?

**Comment by amadeo-alex** [comment] 2024-05-18 17:04
@entirelynutz the general steps I'd say are:
1. remove the original/old HASS.Agent integration (of course it'll require you to remove the devices as well)
2. restart Home Assistant
3. install the forked version of the integration
4. make sure HASS.Agent (client) is running on the PC devices)
5. restart Home Assistant

After doing so they should be discovered in the HA
If not, I'd propose creating a topic on the Discord and doing some additional investigation there.

**Comment by shedman214** [comment] 2024-05-21 17:44
I'm not able to get my media player to show up either. I have added the fork in hacs and restarted HA. It still does not show up for my media player. Do I need to uninstall and reinstall Hass on my PC?

**Comment by aaamoeder** [comment] 2024-05-21 17:55
did the init adjustments and now everything is working again ! thanks !!!

**Comment by shedman214** [comment] 2024-05-21 17:59
> did the init adjustments and now everything is working again ! thanks !!!

what adjustments did you do for it to work?

**Comment by aaamoeder** [comment] 2024-05-21 20:37
> Ok, so, quick&dirty fix for anyone that can/wants edit the files manually :D
> 
> 1. Navigate to "/config/custom_components/hass_agent" - either inside the container or via some editor when using the supervisor enabled HA.
> 2. Edit "__init__.py" file (for example "vi __init__.py")
> 3. Add "async" in following places:
>    a) line 27: "**async** def update_device_info(hass: HomeAssistant, entry: ConfigEntry, new_device_info):"
>    b) line 139: "**async** def updated(message: ReceiveMessage):"
> 4. Add "await" in following places:
>    a) line 124: "**await** update_device_info(hass, entry, response_json)"
>    b) line 144: "**await** update_device_info(hass, entry, payload)"
> 5. Restart Home Assistant
> 
> What I did was do the above changes on version lower than 2024.5.0, confirmed that notifications and media player are working, then I upgraded to 2024.5.0 and tested the same - appears to work as expected.
> 
> Additional images: ![NHdZaU](https://private-user-images.githubusercontent.com/68441479/327392110-9215b843-93a4-43e2-941b-579a2488c35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTQwMDgsIm5iZiI6MTcxNjMxMzcwOCwicGF0aCI6Ii82ODQ0MTQ3OS8zMjczOTIxMTAtOTIxNWI4NDMtOTNhNC00M2UyLTk0MWItNTc5YTI0ODhjMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE3NDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDg4NTM0MTBkZTZiZjYzY2IxMmY1MTc0YjExZDg5NzljMDBhNjE2OTM4OGIxZGY2YzYzY2RkNjk0M2M0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsCzoec5wRQLcrpU3oLtp9lA1kpLX0eXJ3-7CXHKz2g) ![aBulwm](https://private-user-images.githubusercontent.com/68441479/327392919-2b63280d-f268-4bca-b633-11e9060b935f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTQwMDgsIm5iZiI6MTcxNjMxMzcwOCwicGF0aCI6Ii82ODQ0MTQ3OS8zMjczOTI5MTktMmI2MzI4MGQtZjI2OC00YmNhLWI2MzMtMTFlOTA2MGI5MzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE3NDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NWJjMzAyNDdiMjAyZGVjNTRjYTAyOTlhM2Q3YmRiYzNiNWZjODZlYmM2Nzg0ODNiZmJhNDdhYzhmYjNhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ifnhLnn6ospX_KjkBQBQdMiadmbosLg2VOHQnd6hhS0)

@shedman214 these

**Comment by xlyralycanx** [comment] 2024-05-23 21:05
> Ok, so, quick&dirty fix for anyone that can/wants edit the files manually :D
> 
> 1. Navigate to "/config/custom_components/hass_agent" - either inside the container or via some editor when using the supervisor enabled HA.
> 2. Edit "__init__.py" file (for example "vi __init__.py")
> 3. Add "async" in following places:
>    a) line 27: "**async** def update_device_info(hass: HomeAssistant, entry: ConfigEntry, new_device_info):"
>    b) line 139: "**async** def updated(message: ReceiveMessage):"
> 4. Add "await" in following places:
>    a) line 124: "**await** update_device_info(hass, entry, response_json)"
>    b) line 144: "**await** update_device_info(hass, entry, payload)"
> 5. Restart Home Assistant

Worked for me, thank you very much!!

**Comment by aredon** [comment] 2024-06-01 17:33
When is this fix planned on being released?

**Comment by amadeo-alex** [comment] 2024-06-02 07:46
It has been fixed in this(forked) repository. The issue is still open as people tend not to check the closed ones - I'll close it at the end of this week probably.

Please follow those steps for the installation - https://github.com/hass-agent/HASS.Agent-Integration?tab=readme-ov-file#installation

**Comment by aredon** [comment] 2024-06-02 19:36
Well that's forking annoying. :D 

Thanks for the link.

**Closed** 2024-06-09 12:53 UTC
Labels: bug

**Comment by kuligs2** [comment] 2024-08-03 17:51
can confirm that on the latest HA and HASS its not working..
