### ISSUE TITLE
MEDIA_TYPE_MUSIC was used from hass_agent, this is a deprecated constant

### ISSUE THREAD

**Issue by geofffarmer** [hass-agent/HASS.Agent-Integration#18] opened 2024-11-23 15:09 UTC
Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:222
integration: Media Player (documentation, issues)
First occurred: 15:05:59 (1 occurrences)
Last logged: 15:05:59

MEDIA_TYPE_MUSIC was used from hass_agent, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.MUSIC instead, please report it to the author of the 'hass_agent' custom integration

**Comment by amadeo-alex** [comment] 2024-11-27 15:14
Duplicate of https://github.com/hass-agent/HASS.Agent-Integration/issues/11
Let's keep this one open for clarity :)

**Comment by amadeo-alex** [comment] 2024-12-23 15:23
Fixed in 2.1.1 :)

**Closed by amadeo-alex** 2024-12-23 15:23 UTC
Labels: fixed in beta
